### ISSUE TITLE
Implementation of `Radix` for 128-bit integers

### ISSUE THREAD

**Issue by Jovvik** [mpdn/radix-heap#9]
There is no implementation of `Radix` for 128-bit integers, i.e. `i128` and `u128`.

Is there any reason for that or was it just not added after 128-bit integers were added? Adding `radix_int_impl!(i128)` and `radix_int_impl!(u128)` seems to work.

**Comment by mpdn** [comment]
I don't think 128-bit integers were stable at the time I initially wrote this. I'll add it now.
